version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  stationSki-backend:
    depends_on:
      - mysqldb
    image: mustaphabazdeh/5nids2_g9_projet1:latest
    ports:
      - 6869:8088
    volumes:
      - .m2:/root/.m2

volumes:
  db:
  .m2:

